### ISSUE TITLE
No data collected by coverage package

### ISSUE THREAD

**Issue by mariamadalina** [ewjoachim/python-coverage-comment-action#13]
Following the example here in my repo I get the following errors:
ERROR:coverage_comment:Cannot read .coverage files because files are absolute. You need to configure coverage to write relative paths by adding the following option to your coverage configuration file:
[run]
relative_files = true

My <code>pytest.ini</code> looks as:
```
[pytest]
testpaths =
    tests
norecursedirs=dist build .tox scripts
addopts =
    --cov-report term-missing --cov-branch  --cov-report xml --cov-report term --cov=src -vv --strict-markers -rfE
[run]
disable_warnings = no-data-collected

[coverage:run]
relative_files = true
```

**Comment by ewjoachim** [comment]
(Closing for lack of response, but feel free to reopen if you're still experiencing issues)
