### ISSUE TITLE
File not found in the wiki, Skips "Store Pull Request comment to be posted"

### ISSUE THREAD

**Issue by aGuttman** [ewjoachim/python-coverage-comment-action#15]
I'm having trouble understanding what is happening here: https://github.com/aGuttman/e-mission-server/runs/6683601645?check_suite_focus=true

The action creates/edits a PR comment fine, but fails to store any artifacts to track evolution or display a badge. The problem seems to start in "Coverage comment" where I get the warnings:
```
WARNING:coverage_comment:File not found in the wiki's git repository.
WARNING:coverage_comment:Previous coverage results not found, cannot report on evolution.
```

and then "Store Pull Request comment to be posted" is skipped.

I don't know if I'm doing something wrong. I don't understand GitHub actions very well, but the yml files are basically just copy/pasted from the readme, I'm using all the default values, and I'm working with an already generated .coverage file for testing proposes.

If I try to comment out the conditional in "Store Pull Request comment to be posted" it gives the following warning when run:
```
Warning: No files were found with the provided path: python-coverage-comment-action.txt. No artifacts will be uploaded.
```

**Comment by ewjoachim** [comment]
Thanks for your report. It's very possible that there is a bug indeed :)

I'm not sure when I'll have some time on my hands to investigate, so don't get your hopes too high, but I agree that we should investigate.

**Comment by viktorvillalobos** [comment]
Same here

**Comment by ewjoachim** [comment]
Ok, had some time to take a look. Sorry for the delay :)

The idea is that:
- When the action runs on the repo's default branch, you run the test, coverage, and store the file containing your repo's coverage in the wiki (this file is used for generating your readme badge if you want)
- When the action runs on a PR, it pulls that file to compare the PR's coverage to your default branch's coverage.

In your case, as far as I can tell, you didn't merge a PR to your default branch, so you never had an opportunity to store the file in the wiki. Consequently, the tool can tell you how much coverage you have in the PR, but has no way of knowing what your previous coverage level was, and whether it increased or decreased. 
---
> "Store Pull Request comment to be posted" is skipped.

Yeah.
- If you're a repo admin, the GitHub `pull_request` action runs with permissions to post a comment on a PR, so it does so.
- If you're an external contributor, the action has read only access to the repo. What the action does in this case is store the PR comment as a text file in the run artifacts, then run a special action with read-write action (but which doesn't checkout the PR, to avoid security issues). This action will pull the txt file from the artifacts and post it to your PR.

So as long as you're testing as the repo admin, you'll find this step to be skipped. It's unrelated to the other issue.

**Comment by ewjoachim** [comment]
In my humblest opinion, anyone touching GitHub actions should make themselves familiar with this GitHub blog article (and also part 2 and 3): https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by ewjoachim** [comment]
I'll close the issue now but if anything is still unclear, please reopen.
