### ISSUE TITLE
Changing the storage strategy

### ISSUE THREAD

**Issue by ewjoachim** [ewjoachim/python-coverage-comment-action#31]
Continuation from the discussion in #29

So we're thinking about changing the storage strategy from "wiki" to "dedicated branch.

- This will require a major version bump (v3)
- Also, on the v2 branch, make sure we target the v2 docker image
- I think the idea would be that we specify the branch in the actions settings. If not set, we would use a default name (`python-coverage-comment-action-data` ?) we would create an empty branch (as in: `git checkout --orphan <branch>`, `git reset --hard`)
- Optionnal (but if we're rewriting this code anyway) We could always push 3 files : the svg itself (so that will make the private repo work as well) and a json containing details of the coverage run (a floating point coverage percentage with 2 decimal digits so we wouldn't loose too much precision when saying if the rate increase or decreased) and a json for the shields endpoint.
- We would post all the URLs when the action runs:
  - the url to the image directly (and mention that it's the solution for private repos)
  - the url to the dynamic endpoint (and mention that it cannot have a dynamic color, it will always be the color you choose)
  - the url to the json endpoint (and mention that one can override parts of the style)
  - (and maybe the shields pages with the documentation)
- When pushing the branch for the first time, it would be great to also push a README.md. Explain what this branch is, point to the action URL.
- In the documentation, be clear that this action will push to a dedicated branch. This means users may have to tweak existing workflow if those workflow trigger on all branches pushes ?

**Comment by ewjoachim** [comment]
So @kieferro are you interested in giving it a go ? Or do you prefer if I do ? Or any other solution (I'm a pair programming fan, but I don't know if our timezones match :D )

**Comment by kieferro** [comment]
I'm happy to take it over, but it may take me a bit to finish, depending on how I find time for it.
So if you want it done quickly or especially like to take it over, you can do it too.
I think pair programming would have the advantage that we wouldn't have a code review on a large scale. If the location given in your profile is still correct, then time zones shouldn't be a problem. That said, I don't know if we'll manage to agree on a time that suits us both.
Would you have any ideas on how pair programming could be arranged in detail?

**Comment by ewjoachim** [comment]
What would be a good wait to chat with you to setup a date and exchange a link to a videoconferencing tool ? I'm on twitter, reddit, keybase, signal, etc (though I may not have notifications enabled everywhere)

**Comment by kieferro** [comment]
I have sent you an email with contact information.
