### ISSUE TITLE
Docker tag `latest` contains v2, not v3, breaking action.yml

### ISSUE THREAD

**Issue by dato** [ewjoachim/python-coverage-comment-action#47]
It seems to me that after merging perhaps #36, the _latest_ label in the Docker image contains v2 code, and not v3:

```bash
$ docker pull ewjoachim/python:latest
...
Digest: sha256:0b726959b7be0b79442334faa40797dc18535036cfd3d8dcf016475ea2256443
Status: Downloaded newer image for ewjoachim/python-coverage-comment-action:latest

$ docker run --rm -ti --entrypoint /bin/bash ewjoachim/python-coverage-comment-action:latest
root@8336838d94ee:/workdir# grep wiki /usr/local/lib/python3.10/site-packages/coverage_comment/main.py 
    wiki,
    previous_coverage_data_file = wiki.get_file_contents(
    log.info("Saving Badge into the repo wiki")
    wiki.upload_file(
    url = wiki.get_wiki_file_url(
```

This wouldn't matter much, except _action.yml_ specifies `:latest`, not `:v3`:

https://github.com/ewjoachim/python-coverage-comment-action/blob/9a514f2ceccf48e6be062bf4f637a98b515a6f6a/action.yml#L67-L70

Many thanks for your work, it's a great action!

**Comment by kieferro** [comment]
Yes, that doesn't look the way it should be. Thank you very much for the comment. We will look at it as soon as we can.



> Many thanks for your work, it's a great action!

❤️

**Comment by ewjoachim** [comment]
We explicitely disabled pushing latest to "freeze" the action while undergoing the changes between v2 and v3.

See https://github.com/ewjoachim/python-coverage-comment-action/pull/39/files

I'm afraid we may have missed some parts which means the action stopped working if you target the "latest" version" :( If you use `:@v2`, it's supposed to work.

**Comment by ewjoachim** [comment]
Now that https://github.com/ewjoachim/python-coverage-comment-action/pull/52 has been merged, I'm pretty convinced we should be good.

In https://github.com/ewjoachim/python-coverage-comment-action/pull/30, I've been working on fully-automated end-to-end tests that will be run on top of our 100% coverage unit & intergation suite, and I believe it should be enough to be pretty confident it works. I'm still working on the test suite, but it already runs on most use-cases, so I'm quite convinced the action should work as expected on v3.

**Comment by dato** [comment]
Yes, I can confirm it works. Thanks!

**Comment by kieferro** [comment]
:+1:
