### ISSUE TITLE
Allow for optional use of a wiki

### ISSUE THREAD

**Issue by Doggie52** [ewjoachim/python-coverage-comment-action#6]
I'm trying to use this action on a private repository where I don't have the ability to enable the wiki (without upgrading to a paid GH package). It would be great if the use of a wiki would be optional. I understand that without a badge json, you cannot show changes in coverage, but even without that feature, it would be a great action.

**Comment by Doggie52** [comment]
In fact, even if I were to enable the wiki and then disable it, it would not work properly since private wikis are not accessible outside (using raw.githubusercontent).

**Comment by ewjoachim** [comment]
Hm, so what needs to be changed in the action ? If you don't configure it to run on your main branch, then it won't try to store the coverage, and even when it fails to fetch it, it should just ignore the error and skip displaying coverage evolution.

**Comment by Doggie52** [comment]
I think you might be right - I was seeing some exceptions but in the end the comment did display without coverage evolution. I mistook the exceptions for being fatal.
