### ISSUE TITLE
Support private repository wikis

### ISSUE THREAD

**Issue by Doggie52** [ewjoachim/python-coverage-comment-action#7]
Right now, if a repository's wiki is private, this action will not work, since private wikis cannot have their content accessed using raw.githubusercontent.com.

**Comment by Doggie52** [comment]
Working on this in https://github.com/Doggie52/python-coverage-comment-action, will contribute once that works fine.

**Comment by ewjoachim** [comment]
@Doggie52 In case I forget to ping you when it's released, I wanted to let you know that we're working on the v3 of this action, it doesn't use the wiki anymore, and it works on private repos.

Follow #33 for details.
